config/routes.rb
Rails.application.routes.draw do
  
  get "/service-worker.js" => "service_worker#service_worker"
  get "/manifest.json" => "service_worker#manifest"

  get 'membership', to: 'static#membership'
  get 'licences_disclaimer', to: 'static#licences_disclaimer'
  get 'contact', to: 'static#contact'
  get 'usecases', to: 'static#use_cases'
  get 'about', to: 'users#about', as: :about
  get 'faq', to: 'static#faq'
  get 'short_links/free', to: 'short_links#free', as: :free_short_links
  post 'mailing_list', to: 'static#mailing_list'

  patch 'drag/links', to: 'links#reorder', as: :drag_links

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :links, except: :destroy
  resources :users, only: :edit
  resources :short_links
  resources :short_link_redirects, only: %i[show], param: :url_token
  resources :qr_codes
  resources :groups, only: [:edit, :update]

  resources :links, only: [] do
    scope module: "links" do
      resources :short_links, only: %i[ create ]
    end
  end

  root 'static#index'
  get 'search', to: 'search#index'
  get 'analytics', to: 'analytics#index'
  post 'analytics/clicks', to: 'analytics#create'

  namespace :api, defaults: { format: :json } do
    get 'search', to: 'search#index'
    get 'analytics/:id', to: 'analytics#show'
  end

  resources :profiles, only: %i[show edit update], param: :id, path: ''

  get '/r/:url_token', to: redirect('/short_link_redirects/%{url_token}')
end

app/models/user.rb
class User < ApplicationRecord
  is_impressionable
  extend FriendlyId
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         # for Google OmniAuth
         :omniauthable, omniauth_providers: [:google_oauth2]

  has_one_attached :avatar
  has_one_attached :qr_code
  has_many :links, dependent: :destroy
  has_one :profile
  accepts_nested_attributes_for :profile

  friendly_id :username, use: %i[slugged]

  validates :full_name, length: { maximum: 64 }
  validates :description, length: { maximum: 256 }
  validates_format_of :username, :with => /\A[a-z0-9]+\z/i
  validates :username, uniqueness: true
  validate :valid_username

  scope :anonymous_short_links, -> { where(self.links.where(categories: :anonymous_short_link)) }

  def valid_username
    
    restricted_username_list = %(admin root dashboard analytics design settings preferences membership licences_disclaimer contact usecases faq)

    errors.add(:username, ' is restricted.') if restricted_username_list.include?(username)
  end


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      unless User.where(username: auth.info.email.split('@').first).exists?
        user.username = "#{auth.info.email.split('@').first}"
      end
      user.full_name = auth.info.name
      user.avatar_url = auth.info.image
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  def google_oauth2
    user = User.from_omniauth(auth)
    if user.present?
      sign_out_all_scopes
      GenerateLinksForNewUser.new(user).call
      GenerateQrCodeForUser.new(user).call
      flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect user, event: :authentication
    else
      flash[:alert] =
        t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
      redirect_to new_user_session_path
    end
  end

  protected

  def after_omniauth_failure_path_for(_scope)
    new_user_session_path
  end
  
  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || links_path
  end

  private
  
  def auth
    @auth ||= request.env['omniauth.auth']
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  impressionist actions: [:new]
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super

    if resource.save!
      GenerateLinksForNewUser.new(resource).call
      GenerateQrCodeForUser.new(resource).call
    else
      redirect_to new_user_registration_path
    end
  end

  # GET /resource/edit
  def edit
    @should_render_navbar = true
    super
  end

  # PUT /resource
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      GenerateQrCodeForUser.new(resource_updated).call if resource.previous_changes.include?('username')
      set_flash_message_for_update(resource, prev_unconfirmed_email)
      bypass_sign_in resource, scope: resource_name if sign_in_after_change_password?

      respond_with resource, location: after_update_path_for(resource)
    else
      clean_up_passwords resource
      set_minimum_password_length
      redirect_to request.referer, alert: resource.errors.full_messages.join(', ')
    end
  end

  # For omniauth.
  def update_resource(resource, params)
    if resource.provider == 'google_oauth2'
      params.delete('current_password')
      resource.password = params['password']
      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def update_resource(resource, params)
    # Require current password if user is trying to change password.
    return super if params['password']&.present?

    # Allows user to update registration information without password.
    resource.update_without_password(params.except('current_password'))
  end

  def after_update_path_for(_resource)
    request.referrer
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: %i[avatar full_name username description background_color])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    edit_user_path(@user)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # For omniauth.
  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end
  
  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || links_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :index]

  def edit
    @should_render_navbar = true

    links = @user.links.where.not(url: 'https://').order(position: :asc)
    @free_links = links.where(category: "free")
    @social_links = links.where(category: "social")
    unless @free_links.empty?
      @group_name = @free_links.first.group.name
    else
      @group_name = ""
    end
  end

  def show
    if @user.nil?
      redirect_to links_path
    else
      @should_render_navbar_public = false
      impressionist(@user)
      links = @user.links.where.not(url: 'https://').order(position: :asc)
      @free_links = links.where(category: "free")
      @social_links = links.where(category: "social")
      unless @free_links.empty?
        @group_name = @free_links.first.group.name
      else
        @group_name = ""
      end
      set_background_color
    end
  end

  def about
    @user = User.find(1)

    @should_render_navbar_public = true
    impressionist(@user)
    links = @user.links.where.not(url: 'https://').order(position: :asc)
    @free_links = links.where(category: "free")
    @social_links = links.where(category: "social")
    @group_name = @free_links.first.group.name
    set_background_color
    render template: "users/show"
  end

  private

  def set_background_color
    @inject_background_color = "background-color: " + @user.background_color
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_bento_link_button.erb
<%# This is individual table row %>
<% dragActions = "dragstart->drag#dragStart 
                  dragover->drag#dragOver 
                  dragenter->drag#dragEnter 
                  drop->drag#drop 
                  dragend->drag#dragEnd"
   linkClass = "link-card-draggable overflow-visible draggable-mobile " + link_class(link) %>
<%= content_tag(:div, class: linkClass, draggable: false, data: { 
  controller: "drag",
  action: dragActions,
  resource_id: link.id,
  url: "/drag/links",
  parent: parentID
}) do %>

  <button id="moveButton<%= link.id %>" type="button" class="link-action-move hidable btn btn-light w-100 rounded-circle rounded-bottom-0 shadow draggable-hook" onmouseover="showHidable(<%= link.id %>)" onmouseout="hideHidable(<%= link.id %>)"><i class="fa-solid fa-arrows-up-down-left-right"></i></button>
  
  <%= link_to edit_link_path(link), 
    class: "link-action-edit hidable btn btn-light w-100 rounded-circle rounded-top-0 shadow", 
    id: "update-link-#{link.id}", 
    data: { 
      turbo_frame: "modal",
      # parent_id: parentID 
    },
    onmouseover: "showHidable(#{link.id})",
    onmouseout: "hideHidable(#{link.id})" do %>
    <i class="fa-solid fa-pen draggable-hook"></i>
  <% end %>

  <div class="card link-card text-decoration-none" 
    onmouseover="showHidable(<%= link.id %>)" 
    onmouseout="hideHidable(<%= link.id %>)">
    <% if link_class(link) == "link-card-1x3" %>
      <% if link.image.attached? %>
        <%= image_tag(link.image, class: 'card-img-top', loading: 'lazy') %>
      <% else %>
        <%= image_tag('jalur_gemilang_FA_no_sig.jpg', class: 'card-img-top', loading: 'lazy', srcset: { 'jalur_gemilang_FA_no_sig.jpg' => '1x', 'jalur_gemilang_FA_no_sig@2x.jpg' => '2x' }) %>
      <% end %>
    <% end %>
    <div class="link-icon">
      <i class="fa-<%= link.icon_style %> fa-<%= link.icon %> <%= "color--#{link.icon}" if link.social? %>"></i>
    </div>
    <div class="card-body py-0 link-url"><%= link.url %></div>
    <div class="card-body py-0 link-title"><%= link.title %></div>

    <div class="card-body link-cta">
      <%= link_to link_path(link), target: "_blank", class: "btn btn-primary rounded-pill" do %>
        Visit link
      <% end %>
    </div>
  </div>

  <% if false %>
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><i class="fa-<%= link.icon_style %> fa-<%= link.icon %> mr-2 <%= "color--#{link.icon}" if link.social? %>"></i></li>
      <li class="list-group-item"><%= link.title %></li>
      <li class="list-group-item"><%= link.url %></li>
      <li class="list-group-item"><%= link.impressionist_count %> <span class="d-lg-none">clicks</span></li>
    </ul>
  <% end %>
<% end %>

app/views/users/_bento_link_button.html.erb
<%# This is individual table row %>
<% dragActions = "dragstart->drag#dragStart 
                  dragover->drag#dragOver 
                  dragenter->drag#dragEnter 
                  drop->drag#drop 
                  dragend->drag#dragEnd"
   linkClass = "link-card-draggable overflow-visible draggable-mobile " + link_class(link) %>
<%= content_tag(:div, class: linkClass, draggable: false, data: { 
  controller: "drag",
  action: dragActions,
  resource_id: link.id,
  url: "/drag/links",
  parent: parentID
}) do %>

  <button id="moveButton<%= link.id %>" type="button" class="link-action-move hidable btn btn-light w-100 rounded-circle rounded-bottom-0 shadow draggable-hook" onmouseover="showHidable(<%= link.id %>)" onmouseout="hideHidable(<%= link.id %>)"><i class="fa-solid fa-arrows-up-down-left-right"></i></button>
  
  <%= link_to edit_link_path(link), 
    class: "link-action-edit hidable btn btn-light w-100 rounded-circle rounded-top-0 shadow", 
    id: "update-link-#{link.id}", 
    data: { 
      turbo_frame: "modal",
      # parent_id: parentID 
    },
    onmouseover: "showHidable(#{link.id})",
    onmouseout: "hideHidable(#{link.id})" do %>
    <i class="fa-solid fa-pen draggable-hook"></i>
  <% end %>

  <div class="card link-card text-decoration-none" 
    onmouseover="showHidable(<%= link.id %>)" 
    onmouseout="hideHidable(<%= link.id %>)">
    <% if link_class(link) == "link-card-1x3" %>
      <% if link.image.attached? %>
        <%= image_tag(link.image, class: 'card-img-top', loading: 'lazy') %>
      <% else %>
        <%= image_tag('jalur_gemilang_FA_no_sig.jpg', class: 'card-img-top', loading: 'lazy', srcset: { 'jalur_gemilang_FA_no_sig.jpg' => '1x', 'jalur_gemilang_FA_no_sig@2x.jpg' => '2x' }) %>
      <% end %>
    <% end %>
    <div class="link-icon">
      <i class="fa-<%= link.icon_style %> fa-<%= link.icon %> <%= "color--#{link.icon}" if link.social? %>"></i>
    </div>
    <div class="card-body py-0 link-url"><%= link.url %></div>
    <div class="card-body py-0 link-title"><%= link.title %></div>

    <div class="card-body link-cta">
      <%= link_to link_path(link), target: "_blank", class: "btn btn-primary rounded-pill" do %>
        Visit link
      <% end %>
    </div>
  </div>

  <% if false %>
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><i class="fa-<%= link.icon_style %> fa-<%= link.icon %> mr-2 <%= "color--#{link.icon}" if link.social? %>"></i></li>
      <li class="list-group-item"><%= link.title %></li>
      <li class="list-group-item"><%= link.url %></li>
      <li class="list-group-item"><%= link.impressionist_count %> <span class="d-lg-none">clicks</span></li>
    </ul>
  <% end %>
<% end %>

app/views/users/_link_button.erb
<%= link_to link_path(link), target: "_blank", class: "btn-group w-100 d-flex text-decoration-none" do %>
  <div class="btn btn-lg btn-primary flex-shrink-1 col-2 text-center"><i class="fa-<%= link.icon_style %> fa-<%= link.icon %> mr-2"></i></div>
  <div class="btn btn-lg btn-outline-primary w-100 text-start"><%= link.title %></div>
<% end %>

app/views/users/_link_button.html.erb
<%= link_to link_path(link), target: :_blank, rel: 'noopener', class: "btn-group w-100 d-flex text-decoration-none" do %>
  <div class="btn btn-lg btn-primary flex-shrink-1 col-2 text-center"><i class="fa-<%= link.icon_style %> fa-<%= link.icon %> mr-2"></i></div>
  <div class="btn btn-lg btn-outline-primary w-100 text-start"><%= link.title %></div>
<% end %>

app/views/users/_profile.erb
<div class="container my-5 pb-5 text-center">
  <div class="row g-5">
    <div class="col-12 offset-lg-3 col-lg-6">
      <%= image_tag user.avatar, class: "user-avatar object-fit-cover d-block mx-auto my-3 col-3 col-md-4 col-lg-3 rounded-circle" if user.avatar.attached? %>
      <h3><%= user.full_name.nil? ? user.email : user.full_name %></h3>
      <p class="lead">
        <%= user.description %>
      </p>
    </div>
    <% index = 0 # TODO: Iterate throuugh link groups %>
    <div class="col-12 offset-lg-3 col-lg-6">
      <h5><%= @group_name %></h5>
      <div id=<%= "old-links-container-" + index.to_s %>>
        <% @free_links.each do |link| %>
          <%= render "link_button", link: link, parentID: "links-container-" + index.to_s %>
        <% end %>
      </div>
    </div>
    <div class="col-12">
      <div class="grid gap-3 mb-3">
        <% @social_links.each do |link| %>
          <%= link_to link_path(link), target: "_blank", class: "text-decoration-none" do %>
            <%= render "social_link_button", link: link %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container my-5">
  <div class="row">
    <div class="col-12 offset-lg-3 col-lg-6">
      <div class="accordion" id="accordionShare">
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
              Share your profile
            </button>
          </h2>
          <div id="collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionShare">
            <div class="accordion-body text-center">
              <span>Show this QR code to your friends</span>
              <%= image_tag user.qr_code, class: "user-avatar object-fit-cover d-block mx-auto my-3 col-3 col-md-4 col-lg-3 rounded-circle" if user.qr_code.attached? %>
              <% if !@user.username.nil? %>
                <button onclick="copyProfileLink()" class="btn btn-outline-secondary">
                  <i class="bi bi-clipboard-plus me-2"></i>Copy your profile link
                </button>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  function copyProfileLink() {
    /* Copy user profile link into clipboard */
    const app_url = "<%= request.base_url %>"
    const username = "<%= @user.username %>"
    navigator.clipboard.writeText(app_url + "/" + username);
  }
</script>

app/views/users/_profile.html.erb
<div class="container my-5 pb-5 text-center">
  <div class="row g-5">
    <div class="col-12 offset-lg-3 col-lg-6">
      <%= image_tag user.avatar, class: "user-avatar object-fit-cover d-block mx-auto my-3 col-3 col-md-4 col-lg-3 rounded-circle position-relative" if user.avatar.attached? %>
      <% if @user.username == "rudzainy" %>
        <span class="badge rounded-pill bg-primary">
          <i class="fas fa-circle-check me-2"></i>Verified Gugler!
        </span>
      <% end %>
      <h3><%= user.full_name.nil? ? user.email : user.full_name %></h3>
      <p class="lead">
        <%= user.description %>
      </p>
    </div>
    <% index = 0 # TODO: Iterate throuugh link groups %>
    <div class="col-12 offset-lg-3 col-lg-6">
      <h5><%= @group_name %></h5>
      <div id=<%= "old-links-container-" + index.to_s %>>
        <% @free_links.each do |link| %>
          <%= render "link_button", link: link, parentID: "links-container-" + index.to_s %>
        <% end %>
      </div>
    </div>
    <div class="col-12">
      <div class="grid gap-3 mb-3">
        <% @social_links.each do |link| %>
          <%= link_to link_path(link), target: "_blank", class: "text-decoration-none" do %>
            <%= render "social_link_button", link: link %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container my-5">
  <div class="row">
    <div class="col-12 offset-lg-3 col-lg-6">
      <div class="accordion" id="accordionShare">
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
              Share <%= user_signed_in? && @user == current_user ? "your" : "this" %> profile
            </button>
          </h2>
          <div id="collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionShare">
            <div class="accordion-body text-center">
              <% if user.qr_code.attached? %>
                <p>Share this QR code to your friends</p>
                <%= image_tag user.qr_code, class: "user-avatar object-fit-cover d-block mx-auto my-3 col-3 col-md-4 col-lg-3 rounded-circle" %>
              <% end %>
              <% if !@user.username.nil? %>
                <button onclick="copyProfileLink()" class="btn btn-outline-secondary" id="copyProfileLinkButton">
                  <i class="bi bi-clipboard-plus me-2"></i>Copy <%= user_signed_in? && @user == current_user ? "your" : "this" %> profile link
                </button>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  // Copy user profile link into clipboard.
  function copyProfileLink() {
    const app_url = "<%= request.base_url %>";
    const username = "<%= @user.username %>";
    navigator.clipboard.writeText(app_url + "/" + username);
    document.getElementById("copyProfileLinkButton").innerHTML = "<i class='fas fa-thumbs-up me-2'></i>Copied to your clipboard!"
  }
</script>

app/views/users/_profile_preview.erb
<div class="container my-5 pb-5 text-center">
  <div class="row g-5">
    <div class="col-12">
      <%= image_tag user.avatar, class: "user-avatar object-fit-cover d-block mx-auto my-3 col-3 rounded-circle" if user.avatar.attached? %>
      <h3><%= user.full_name.nil? ? user.email : user.full_name %></h3>
      <p class="lead mb-5">
        <%= user.description %>
      </p>
    </div>
    <div class="col-12">
      <div class="grid gap-2 mb-3">
        <% @social_links.each do |link| %>
          <%= link_to link_path(link), target: "_blank", class: "text-decoration-none" do %>
            <%= render "social_link_button", link: link %>
          <% end %>
        <% end %>
      </div>
    </div>
    <% index = 0 # TODO: Iterate throuugh link groups %>
    <div class="col-12">
      <h5><%= @group_name %></h5>
      <div id=<%= "links-container-" + index.to_s %>>
        <% @free_links.each do |link| %>
          <%= render "bento_link_button", link: link, parentID: "links-container-" + index.to_s %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_profile_preview.html.erb
<div class="container my-5 pb-5 text-center">
  <div class="row g-5">
    <div class="col-12">
      <%= image_tag user.avatar, class: "user-avatar object-fit-cover d-block mx-auto my-3 col-3 rounded-circle" if user.avatar.attached? %>
      <h3><%= user.full_name.nil? ? user.email : user.full_name %></h3>
      <p class="lead mb-5">
        <%= user.description %>
      </p>
    </div>
    <div class="col-12">
      <div class="grid gap-2 mb-3">
        <% @social_links.each do |link| %>
          <%= link_to link_path(link), target: "_blank", class: "text-decoration-none" do %>
            <%= render "social_link_button", link: link %>
          <% end %>
        <% end %>
      </div>
    </div>
    <% index = 0 # TODO: Iterate throuugh link groups %>
    <div class="col-12">
      <h5><%= @group_name %></h5>
      <div id=<%= "links-container-" + index.to_s %>>
        <% @free_links.each do |link| %>
          <%= render "bento_link_button", link: link, parentID: "links-container-" + index.to_s %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_social_link_button.erb
<div class="btn btn-lg btn-primary text-center <%= "border--#{link.icon} bg--#{link.icon}" %>"><i class="fa-<%= link.icon_style %> fa-<%= link.icon %> mr-2"></i></div>

app/views/users/_social_link_button.html.erb
<div class="btn btn-lg btn-primary text-center <%= "border--#{link.icon} bg--#{link.icon}" %>"><i class="fa-<%= link.icon_style %> fa-<%= link.icon %> mr-2"></i></div>

app/views/users/show.html.erb
<%= render 'profile', user: @user %>

<div class="container-fluid text-center">
  <% if user_signed_in? %> 
    <% if @user == current_user %>
      <%= link_to "Profile page settings", edit_user_path(current_user), class: "btn btn-sm btn-outline-secondary" %>
    <% else %>
      <%= link_to "Go to your profile page", user_path(current_user), class: "btn btn-sm btn-outline-secondary" %>
    <% end %>
  <% else %>
    <%= link_to new_user_session_path, class: "btn btn-small btn-outline-secondary mb-2" do %>
      Build your own bio with gugel.my
    <% end %>
  <% end %>
</div>