config/routes.rb
Rails.application.routes.draw do
  
  get "/service-worker.js" => "service_worker#service_worker"
  get "/manifest.json" => "service_worker#manifest"

  get 'membership', to: 'static#membership'
  get 'licences_disclaimer', to: 'static#licences_disclaimer'
  get 'contact', to: 'static#contact'
  get 'usecases', to: 'static#use_cases'
  get 'about', to: 'users#about', as: :about
  get 'faq', to: 'static#faq'
  get 'short_links/free', to: 'short_links#free', as: :free_short_links
  post 'mailing_list', to: 'static#mailing_list'

  patch 'drag/links', to: 'links#reorder', as: :drag_links

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :links, except: :destroy
  resources :users, only: :edit
  resources :short_links
  resources :short_link_redirects, only: %i[show], param: :url_token
  resources :qr_codes
  resources :groups, only: [:edit, :update]

  resources :links, only: [] do
    scope module: "links" do
      resources :short_links, only: %i[ create ]
    end
  end

  root 'static#index'
  get 'search', to: 'search#index'
  get 'analytics', to: 'analytics#index'
  post 'analytics/clicks', to: 'analytics#create'

  namespace :api, defaults: { format: :json } do
    get 'search', to: 'search#index'
    get 'analytics/:id', to: 'analytics#show'
  end

  resources :profiles, only: %i[show edit update], param: :id, path: ''

  get '/r/:url_token', to: redirect('/short_link_redirects/%{url_token}')
end

app/models/short_link.rb
class ShortLink < ApplicationRecord
  is_impressionable
  has_one_attached :qr_code
  belongs_to :link

  after_create :generate_qr_code

  private

  def generate_qr_code
    url = "#{ENV["APP_URL"]}/short_link_redirects/#{url_token}"
    qrcode = ::RQRCode::QRCode.new(url)

    # NOTE: showing with default options specified explicitly
    qr_png = qrcode.as_png(
      bit_depth: 1,
      border_modules: 4,
      color_mode: ChunkyPNG::COLOR_GRAYSCALE,
      color: "black",
      file: nil,
      fill: "white",
      module_px_size: 6,
      resize_exactly_to: false,
      resize_gte_to: false,
      size: 120
    )

    qr_code.attach(
      io: StringIO.new(qr_png.to_s),
      filename: "short-link-#{id}-qrcode.png",
      content_type: "image/png"
    )
  end
end

app/controllers/links/short_links_controller.rb
class Links::ShortLinksController < ApplicationController

  def create
    link = Link.find(params[:link_id])

    ShortLink.create(
      link: link,
      statistics_token: SecureRandom.urlsafe_base64(4),
      url_token: SecureRandom.urlsafe_base64(4)
    )

    redirect_to links_path
  end
end

app/controllers/short_links_controller.rb
include Recaptcha::Adapters::ViewMethods
include Recaptcha::Adapters::ControllerMethods

class ShortLinksController < ApplicationController
  impressionist actions: [:free]
  before_action :authenticate_user!, only: [:index]

  def index
    @should_render_navbar = true
    # Find all current_user's short_links
    @links = Link.all.where(category: 2, user_id: current_user.id)
    @short_link = ShortLink.new
  end

  def new
    @short_link = ShortLink.new
  end

  def free
    redirect_to "/"
    # unless user_signed_in?
    #   @show_checkbox_recaptcha = true
    # end
    # @short_link = ShortLink.new
  end

  def create
    if user_signed_in?
      link = current_user.links.create!(
        url: url,
        category: 2,
      )
    
      @short_link = ShortLink.new
  
      @shorten_link = ShortLink.create!(
        link: link,
        statistics_token: SecureRandom.urlsafe_base64(4),
        url_token: SecureRandom.urlsafe_base64(4)
      )
      
      render turbo_stream: turbo_stream.prepend("short-links-container", partial: "short_links/table_row", locals: {link: link}, notice: "Link was successfully shorten.") 
    else
      success = verify_recaptcha(action: 'free_shortlinks', minimum_score: 0.5, secret_key: ENV['RECAPTCHA_SITE_KEY'])
      checkbox_success = verify_recaptcha unless success
      if success || checkbox_success
        link = Link.create!(
          url: url,
          category: 2
        )
        if link
          @short_link = ShortLink.new
  
          @shorten_link = ShortLink.create!(
            link: link,
            statistics_token: SecureRandom.urlsafe_base64(4),
            url_token: SecureRandom.urlsafe_base64(4)
          )
        end
      else
        if !success
          @show_checkbox_recaptcha = true
        end
        render 'free'
      end
    end
  end

  private

  def url
    params[:url]
  end
end

app/helpers/short_links_helper.rb
module ShortLinksHelper
end

app/views/short_links/_form.html.erb
<%= simple_form_for @short_links do |f| %>
  <div class="row">
    <label for="url" class="col-sm-3 col-form-label">URL</label>
    <div class="col-sm-9">
      <div class="input-group flex-nowrap">
        <span class="input-group-text h-50"><%= base_url%>/</span>
        <%= f.input :url, placeholder: sanitize_link(@short_links.url), input_html: { value: sanitize_link(@short_links.url)}, label: false, class:"form-control rounded-start-0 high-z" %>
      </div>
      <% if @show_checkbox_recaptcha %>
        <%= recaptcha_tags %>
      <% else %>
        <%= recaptcha_v3(action: 'anonymous_shortlink', site_key: ENV['RECAPTCHA_SITE_KEY_V3']) %>
      <% end %>
    </div>
  </div>
  <%= f.submit "Shorten Link", class:"btn btn-primary me-auto shadow" %>
<% end %>

app/views/short_links/_table_row.html.erb
<%# This is the individual table row %>
<tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
  <% if link.nil? %>
    <%# form to create link %>
    <td class="px-6 py-4 text-center"></td>
    <td class="px-6 py-4"></td>
    <td class="px-6 py-4"></td>
    <td class="px-6 py-4"></td>
  <% else %>
    <td class="px-6 py-4 text-center">
      <i class="fas fa-grip-lines text-gray-500 dark:text-gray-400"></i>
    </td>
    <td class="px-6 py-4">
      <div class="text-gray-900 dark:text-white"><%= link.url %></div>
      <% unless link.title.blank? %>
        <div class="text-sm text-gray-500 dark:text-gray-400">(<%= link.title %>)</div>
      <% end %>
    </td>
    <td class="px-6 py-4 font-medium text-gray-900 dark:text-white"><%= link.short_links.first.url_token %></td>
    <td class="px-6 py-4"><%= link.short_links.first.impressionist_count %></td>
  <% end %>
  <td class="px-6 py-4">
    <div class="flex">
      <%= link_to edit_link_path(link), 
                  class: "text-red-700 hover:text-white border border-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-3 py-2 text-center dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-600 dark:focus:ring-red-900", 
                  id: "update-link-#{link.id}", 
                  data: { turbo_frame: "modal" } do %>
        <i class="fas fa-trash-can mr-2"></i>Delete
      <% end %>
    </div>
  </td>
</tr>

app/views/short_links/_table_row_mobile.html.erb
<%# This is the individual link card %>
<%= turbo_frame_tag "edit_link_mobile_#{link.id}" do %>
  <% unless link.empty? %>
    <li class="list-group-item d-flex justify-content-between align-items-start">
      <i class="fa-<%= link.icon_style %> fa-<%= link.icon %> mr-3 mt-3 <%= "color--#{link.icon}" if link.social? %>"></i> 
      <div class="ms-3 flex-fill overflow-hidden">
        <small><%= link.title %></small><br>
        <%= sanitize_link(link.url) %>
      </div>
      <div class="ms-3 mt-2"><i class="fas fa-hand-pointer me-2 text-secondary"></i><%= link.impressionist_count %></div>
      <%= link_to edit_link_path(link), 
                  class: "btn btn-outline-primary btn-sm ms-3 mt-2", 
                  id: "update-link-#{link.id}", 
                  remote: true,
                  data: { turbo_frame: "modal" } do %>
        <i class="bi bi-pencil-fill"></i>
      <% end %>
    </li>
  <% else %>
    <li class="list-group-item d-flex justify-content-end">
      <%= link_to edit_link_path(link), 
                  class: "btn btn-outline-primary btn-sm", 
                  id: "update-link-#{link.id}", 
                  remote: true,
                  data: { turbo_frame: "modal" } do %>
        <i class="bi bi-pencil-fill"></i>
      <% end %>
    </li>
  <% end %>
<% end %>

app/views/short_links/create.html.erb
<%= turbo_frame_tag "shorten_link_container" do %>
  <%= simple_form_for @shorten_link.link.url do |f| %>
    <div class="mb-3">
      <%= text_field_tag :url, @shorten_link.link.url, label: false, class:"form-control rounded high-z text-center" %>
      <div id="longUrlHelp" class="form-text text-center d-flex justify-content-between flex-nowrap px-5">
        <div class="overflow-hidden d-inline-block flex-fill text-nowrap">Paste your looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo</div><div  class="d-inline-block flex-fill text-nowrap">ooooooong URL here<i class="fas fa-hand-point-up ms-2"></i>
        </div>
      </div>
      <% if @show_checkbox_recaptcha %>
        <%= recaptcha_tags %>
      <% else %>
        <%= recaptcha_v3(action: 'anonymous_shortlink', site_key: ENV['RECAPTCHA_SITE_KEY_V3']) %>
      <% end %>
    </div>
    <%= f.submit "Shorten Link", class:"btn btn-warning mx-auto shadow" %>
  <% end %>
  <div class="row mt-5">
    <div class="col-12 col-md-4 offset-md-4">
      <div class="card text-center">
        <div class="card-header">
          Here's your short URL
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= request.base_url %>/r/<%= @shorten_link.url_token %></h5>
          <p class="card-text">Share this with the world!</p>
          <button id="copyShortLinkButton" onclick="copyShortLink()" class="btn btn-outline-warning">
            <i class="bi bi-clipboard-plus me-2"></i>Copy your new short link
          </button>
        </div>
        <div class="card-footer text-body-secondary">
          <%= link_to "Become a member", new_user_registration_path, class: "link-warning" %> when you need more advanced features for your short links.
        </div>
      </div>
    </div>
  </div>
  <script>
    function copyShortLink() {
      /* Copy short link into clipboard */
      const app_url = "<%= request.base_url %>";
      const short_url = "<%= @shorten_link.url_token %>";
      navigator.clipboard.writeText(app_url + "/r/" + short_url);
      this.value = "Link copied!"
      document.getElementById("copyShortLinkButton").innerHTML = "<i class='fas fa-thumbs-up me-2'></i>Copied to your clipboard!"
    }
  </script>
<% end %>

app/views/short_links/free.html.erb
<div class="container mb-5">
  <header class="text-center py-5 bg-white rounded-5 shadow-lg">
    <div class="px-3 py-5 pb-md-4 mx-auto">
      <%= image_tag "illustrations/Leader-nobg.png", class: "img-fluid mb-3" %>
      <h1 class="display-4 fw-normal text-body-emphasis text-center text-warning">Shorten a Link</h1>
      <p class="fs-5 text-body-secondary lead text-center">Free by default.</p>
      
      <%= turbo_frame_tag "shorten_link_container" do %>
        <%= simple_form_for @short_link do |f| %>
          <div class="mb-3">
            <%= text_field_tag :url, nil, label: false, autofocus: true, class:"form-control rounded high-z text-center" %>
            <div id="longUrlHelp" class="form-text text-center d-flex justify-content-between flex-nowrap px-5">
              <div class="overflow-hidden d-inline-block flex-fill text-nowrap">Paste your looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo</div><div class="d-inline-block flex-fill text-nowrap">ooooooong URL here<i class="fas fa-hand-point-up ms-2"></i></div></div>

            <div class="mx-auto">
              <% if @show_checkbox_recaptcha %>
                <%= recaptcha_tags %>
              <% else %>
                <%= recaptcha_v3(action: 'free_shortlinks', site_key: ENV['RECAPTCHA_SITE_KEY']) %>
              <% end %>
            </div>
          </div>
          <%= f.submit "Shorten Link", class:"btn btn-warning mx-auto shadow" %>
        <% end %>
      <% end %>
    </div>
  </header>
</div>

<%= render "layouts/footer" %>

app/views/short_links/index.html.erb
<%#
    This page should show all user's short links. 
    Short links are sorted by view count. 
    Web view should show data table to focus on analytics. 
    Mobile view should be more compact. 
%>

<%= render partial: "users/profile_statistics" %>
<div class="container mt-5">
  <div class="row">
    <div class="col">
      <h1>Manage your short links</h1>
    </div>
  </div>
</div>

<div class="container mt-5">
  <h5>Short Links</h5>
</div>

<div class="container">
  <div class="card">
    <div class="card-body">
      <%= turbo_frame_tag "shorten_link_container" do %>
        <%= simple_form_for @short_link do |f| %>
          <div class="mb-3">
            <%= text_field_tag :url, nil, label: false, autofocus: true, class:"form-control rounded high-z" %>
            <%= hidden_field_tag :user_id, current_user.id %>
            <div id="longUrlHelp" class="form-text d-flex justify-content-between flex-nowrap px-2">
              <div class="overflow-hidden d-inline-block flex-fill text-nowrap">Paste your looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo</div><div class="d-inline-block flex-fill text-nowrap">ooooooong URL here<i class="fas fa-hand-point-up ms-2"></i></div></div>
          </div>
          <%= f.submit "Shorten Link", class:"btn btn-warning mx-auto shadow" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class="container my-5">
  <div class="card table-responsive">
    <table class="table table-hover align-middle mb-0">
      <thead class="table-primary">
        <tr>
          <th scope="col" class="text-center"></th>
          <th scope="col" class="flex-grow-1">Long URL</th>
          <th scope="col">Short URL</th>
          <th scope="col">Clicks</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody id="short-links-container">
        <% @links.each do |link| %>
          <%# This is the individual table row %>
          <%= render "short_links/table_row", link: link %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="container">
  <div class="alert alert-info" role="alert">
    <i class="fas fa-lightbulb me-2"></i>Short links format: <strong>https://gugel.my/r/<span class="text-primary">short_url</span></strong>
  </div>
</div>

app/views/short_links/new.html.erb
<div class="container mb-5">
  <header class="text-center py-5 bg-white rounded-5 shadow-lg">
    <div class="px-3 py-5 pb-md-4 mx-auto">
      <%= image_tag "illustrations/Leader-nobg.png", class: "img-fluid mb-3" %>
      <h1 class="display-4 fw-normal text-body-emphasis text-center text-warning">Shorten a Link</h1>
      <p class="fs-5 text-body-secondary lead text-center">Free by default.</p>
      
      <%= turbo_frame_tag "shorten_link_container" do %>
        <%= simple_form_for @short_link do |f| %>
          <div class="mb-3">
            <%= text_field_tag :url, nil, label: false, autofocus: true, class:"form-control rounded high-z text-center" %>
            <div id="longUrlHelp" class="form-text text-center d-flex justify-content-between flex-nowrap px-5">
              <div class="overflow-hidden d-inline-block flex-fill text-nowrap">Paste your looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo</div><div  class="d-inline-block flex-fill text-nowrap">ooooooong URL here<i class="fas fa-hand-point-up ms-2"></i></div></div>
          </div>
          <%= f.submit "Shorten Link", class:"btn btn-warning mx-auto shadow" %>
        <% end %>
      <% end %>
    </div>
  </header>
</div>

<%= render "layouts/footer" %>